; Zombie Mod Infection Plugins

; Main Plugin
zombie_mod_infection10.amxx debug              

; API
cs_ham_bots_api.amxx
cs_teams_api.amxx
cs_weap_models_api.amxx

; Core Plugins
zmod_restrictions.amxx
zmod_remove_entities.amxx
zmod_admin_menu.amxx
zmod_sky.amxx
zmod_map_lightning.amxx
zmod_auto_restart.amxx
zmod_buyammo.amxx
zmod_human_unlimited_ammo.amxx
zmod_nightvision.amxx

; Sub-Plugins (you can add your own sub-plugins here)